# the high level policy
policy:
  approval:
    - or:
      - security-team or reliability has approved
      - has valid signatures by security-team or reliability
      - author is renovate-bot or flowzone-app
      - deployment ref is main or master

# the list of rules
approval_rules:

  - name: security-team or reliability has approved
    requires:
      count: 1
      users: []
      organizations: []
      teams:
        - "product-os/security-team"
        - "product-os/reliability"
    methods:
      github_review: true
      github_review_comment_patterns:
        - '/deploy'

  - name: has valid signatures by security-team or reliability
    if:
      # "has_valid_signatures_by" is satisfied if the commits in the pull request
      # all have git commit signatures that have been verified by GitHub, and
      # the authenticated signatures are attributed to a user in the users list
      # or belong to a user in any of the listed organizations or teams.
      has_valid_signatures_by:
        users:
          - "basejump-app"
        organizations: []
        teams:
          - "product-os/security-team"
          - "product-os/reliability"
      # Only applies to the test environment
      environment:
        matches:
          - test
    requires:
      count: 0

  # Do not require approvals for renovate or flowzone
  - name: author is renovate-bot or flowzone-app
    if:
      # "only_has_contributors_in" is satisfied if all of the commits on the
      # pull request are authored and committed by users in the users list or
      # that belong to any of the listed organizations or teams.
      only_has_contributors_in:
        users:
          - "balena-renovate[bot]"
          - "flowzone-app[bot]"
          # This account is the Git committer for all web commits (merge/revert/edit/etc...) made on GitHub.com.
          # https://github.com/web-flow
          # Removate rebases via web-flow so we must allow it as a committer. It will never be an author.
          - "web-flow"
      # Only applies to the test environment
      environment:
        matches:
          - test
    requires:
      count: 0

  # Do not require approvals for deployments from main or master branches
  - name: deployment ref is main or master
    if:
      ref_patterns:
        - main
        - master
    requires:
      count: 0
